[build]
  command = "gatsby build"
  publish = "public/"

[template.environment]
  GATSBY_FLOTIQ_API_KEY="56441ef26a1f102c61b235596d493977"
  SNIPCART_API_KEY="YjllMDMzYjEtMDc5NS00ZDExLThlYWMtOWNjNDVjNmFmMDZlNjM3NDY1MjEyMzM2NjA1NjMz"
